name: manage-azure-policy-a530569f
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'initiatives/CIS_Microsoft_Azure_Foundations_Benchmark_1.1.0_1a5bb27d-173f-493e-9568-eb56638dde4d/**'
#      - 'initiatives/Enable_Monitoring_in_Azure_Security_Center_1f3afdf9-d0c9-4c3d-847f-89da613e70a8/**'
#      - .github/workflows/manage-azure-policy-a530569f.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_a530569f}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          initiatives/CIS_Microsoft_Azure_Foundations_Benchmark_1.1.0_1a5bb27d-173f-493e-9568-eb56638dde4d/**
          initiatives/Enable_Monitoring_in_Azure_Security_Center_1f3afdf9-d0c9-4c3d-847f-89da613e70a8/**
